dist: xenial
language: minimal
git:
  depth: 1
  submodules: false
script:
  - sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y
  - sudo apt-get update -q
  - sudo apt-get install gcc-7 g++-7 -y
  - git submodule update --init --recursive --depth 500 || exit 1
  - mkdir -p /tmp/qemu-static/build
  - sudo mount -t tmpfs tmpfs /tmp/qemu-static/build
  - pushd /tmp/qemu-static/build
  - >
      ${TRAVIS_BUILD_DIR}/qemu/configure
      --prefix=/tmp/qemu-static/local
      --interp-prefix=/tmp/qemu-static/local/gnemul
      --target-list=aarch64-softmmu,x86_64-softmmu
      --cc=gcc-7
      --cxx=g++-7
      --static
      --disable-system
      --disable-user
      --disable-linux-user
      --disable-bsd-user
      --disable-docs
      --disable-guest-agent
      --disable-guest-agent-msi
      --disable-pie
      --disable-modules
      --disable-debug-tcg
      --disable-debug-info
      --disable-sparse
      --disable-gnutls
      --disable-nettle
      --disable-gcrypt
      --disable-auth-pam
      --disable-sdl
      --disable-gtk
      --disable-vte
      --disable-curses
      --disable-vnc
      --disable-vnc-sasl
      --disable-vnc-jpeg
      --disable-vnc-png
      --disable-cocoa
      --disable-virtfs
      --disable-mpath
      --disable-xen
      --disable-xen-pci-passthrough
      --disable-brlapi
      --disable-curl
      --disable-membarrier
      --disable-fdt
      --disable-bluez
      --disable-kvm
      --disable-hax
      --disable-hvf
      --disable-whpx
      --disable-rdma
      --disable-pvrdma
      --disable-vde
      --disable-netmap
      --disable-linux-aio
      --disable-cap-ng
      --disable-attr
      --disable-vhost-net
      --disable-vhost-crypto
      --disable-spice
      --disable-rbd
      --disable-libiscsi
      --disable-libnfs
      --disable-smartcard
      --disable-libusb
      --disable-live-block-migration
      --disable-usb-redir
      --disable-lzo
      --disable-snappy
      --disable-bzip2
      --disable-lzfse
      --disable-seccomp
      --disable-coroutine-pool
      --disable-glusterfs
      --disable-tpm
      --disable-libssh2
      --disable-numa
      --disable-libxml2
      --disable-tcmalloc
      --disable-jemalloc
      --disable-avx2
      --disable-replication
      --disable-vhost-vsock
      --disable-opengl
      --disable-virglrenderer
      --disable-xfsctl
      --disable-qom-cast-debug
      --disable-tools
      --disable-vxhs
      --disable-bochs
      --disable-cloop
      --disable-dmg
      --disable-qcow1
      --disable-vdi
      --disable-vvfat
      --disable-qed
      --disable-parallels
      --disable-sheepdog
      --disable-crypto-afalg
      --disable-vhost-user
      --disable-capstone
      --disable-debug-mutex
      --disable-libpmem
      --enable-system
      --enable-fdt
      --enable-kvm
      --enable-vhost-crypto
      --enable-vhost-net
      --enable-vhost-scsi
      --enable-vhost-user
      --enable-vhost-vsock
      --enable-avx2
      --extra-cflags=' -O3 -fno-semantic-interposition -falign-functions=32 -D_FORTIFY_SOURCE=2 -fPIE -fuse-ld=gold'
      --extra-ldflags=' -pie -z noexecstack -z relro -z now'
  - popd
  - make -j $(nproc) -C /tmp/qemu-static/build
  - make -j $(nproc) -C /tmp/qemu-static/build install
  - tree /tmp/qemu-static/local
