dist: xenial
language: minimal
addons:
  update: true
  sources:
    - ubuntu-toolchain-r-test
  apt:
    packages:
    - gcc-7
    - g++-7
    - make
git:
  depth: 1
  submodules: false
env:
  global:
    - CONFIG="--cc=gcc-7 --cxx=g++-7"
    - CONFIG="${CONFIG} --prefix=/tmp/qemu-static/local"
    - CONFIG="${CONFIG} --interp-prefix=/tmp/qemu-static/local/gnemul"
    - CONFIG="${CONFIG} --target-list=aarch64-softmmu,x86_64-softmmu"
    - CONFIG="${CONFIG} --static"
    - CONFIG="${CONFIG} --disable-system"
    - CONFIG="${CONFIG} --disable-user"
    - CONFIG="${CONFIG} --disable-linux-user"
    - CONFIG="${CONFIG} --disable-bsd-user"
    - CONFIG="${CONFIG} --disable-docs"
    - CONFIG="${CONFIG} --disable-guest-agent"
    - CONFIG="${CONFIG} --disable-guest-agent-msi"
    - CONFIG="${CONFIG} --disable-pie"
    - CONFIG="${CONFIG} --disable-modules"
    - CONFIG="${CONFIG} --disable-debug-tcg"
    - CONFIG="${CONFIG} --disable-debug-info"
    - CONFIG="${CONFIG} --disable-sparse"
    - CONFIG="${CONFIG} --disable-gnutls"
    - CONFIG="${CONFIG} --disable-nettle"
    - CONFIG="${CONFIG} --disable-gcrypt"
    - CONFIG="${CONFIG} --disable-auth-pam"
    - CONFIG="${CONFIG} --disable-sdl"
    - CONFIG="${CONFIG} --disable-gtk"
    - CONFIG="${CONFIG} --disable-vte"
    - CONFIG="${CONFIG} --disable-curses"
    - CONFIG="${CONFIG} --disable-vnc"
    - CONFIG="${CONFIG} --disable-vnc-sasl"
    - CONFIG="${CONFIG} --disable-vnc-jpeg"
    - CONFIG="${CONFIG} --disable-vnc-png"
    - CONFIG="${CONFIG} --disable-cocoa"
    - CONFIG="${CONFIG} --disable-virtfs"
    - CONFIG="${CONFIG} --disable-mpath"
    - CONFIG="${CONFIG} --disable-xen"
    - CONFIG="${CONFIG} --disable-xen-pci-passthrough"
    - CONFIG="${CONFIG} --disable-brlapi"
    - CONFIG="${CONFIG} --disable-curl"
    - CONFIG="${CONFIG} --disable-membarrier"
    - CONFIG="${CONFIG} --disable-fdt"
    - CONFIG="${CONFIG} --disable-bluez"
    - CONFIG="${CONFIG} --disable-kvm"
    - CONFIG="${CONFIG} --disable-hax"
    - CONFIG="${CONFIG} --disable-hvf"
    - CONFIG="${CONFIG} --disable-whpx"
    - CONFIG="${CONFIG} --disable-rdma"
    - CONFIG="${CONFIG} --disable-pvrdma"
    - CONFIG="${CONFIG} --disable-vde"
    - CONFIG="${CONFIG} --disable-netmap"
    - CONFIG="${CONFIG} --disable-linux-aio"
    - CONFIG="${CONFIG} --disable-cap-ng"
    - CONFIG="${CONFIG} --disable-attr"
    - CONFIG="${CONFIG} --disable-vhost-net"
    - CONFIG="${CONFIG} --disable-vhost-crypto"
    - CONFIG="${CONFIG} --disable-spice"
    - CONFIG="${CONFIG} --disable-rbd"
    - CONFIG="${CONFIG} --disable-libiscsi"
    - CONFIG="${CONFIG} --disable-libnfs"
    - CONFIG="${CONFIG} --disable-smartcard"
    - CONFIG="${CONFIG} --disable-libusb"
    - CONFIG="${CONFIG} --disable-live-block-migration"
    - CONFIG="${CONFIG} --disable-usb-redir"
    - CONFIG="${CONFIG} --disable-lzo"
    - CONFIG="${CONFIG} --disable-snappy"
    - CONFIG="${CONFIG} --disable-bzip2"
    - CONFIG="${CONFIG} --disable-lzfse"
    - CONFIG="${CONFIG} --disable-seccomp"
    - CONFIG="${CONFIG} --disable-coroutine-pool"
    - CONFIG="${CONFIG} --disable-glusterfs"
    - CONFIG="${CONFIG} --disable-tpm"
    - CONFIG="${CONFIG} --disable-libssh2"
    - CONFIG="${CONFIG} --disable-numa"
    - CONFIG="${CONFIG} --disable-libxml2"
    - CONFIG="${CONFIG} --disable-tcmalloc"
    - CONFIG="${CONFIG} --disable-jemalloc"
    - CONFIG="${CONFIG} --disable-avx2"
    - CONFIG="${CONFIG} --disable-replication"
    - CONFIG="${CONFIG} --disable-vhost-vsock"
    - CONFIG="${CONFIG} --disable-opengl"
    - CONFIG="${CONFIG} --disable-virglrenderer"
    - CONFIG="${CONFIG} --disable-xfsctl"
    - CONFIG="${CONFIG} --disable-qom-cast-debug"
    - CONFIG="${CONFIG} --disable-tools"
    - CONFIG="${CONFIG} --disable-vxhs"
    - CONFIG="${CONFIG} --disable-bochs"
    - CONFIG="${CONFIG} --disable-cloop"
    - CONFIG="${CONFIG} --disable-dmg"
    - CONFIG="${CONFIG} --disable-qcow1"
    - CONFIG="${CONFIG} --disable-vdi"
    - CONFIG="${CONFIG} --disable-vvfat"
    - CONFIG="${CONFIG} --disable-qed"
    - CONFIG="${CONFIG} --disable-parallels"
    - CONFIG="${CONFIG} --disable-sheepdog"
    - CONFIG="${CONFIG} --disable-crypto-afalg"
    - CONFIG="${CONFIG} --disable-vhost-user"
    - CONFIG="${CONFIG} --disable-capstone"
    - CONFIG="${CONFIG} --disable-debug-mutex"
    - CONFIG="${CONFIG} --disable-libpmem"
    - CONFIG="${CONFIG} --enable-system"
    - CONFIG="${CONFIG} --enable-fdt"
    - CONFIG="${CONFIG} --enable-kvm"
    - CONFIG="${CONFIG} --enable-vhost-crypto"
    - CONFIG="${CONFIG} --enable-vhost-net"
    - CONFIG="${CONFIG} --enable-vhost-scsi"
    - CONFIG="${CONFIG} --enable-vhost-user"
    - CONFIG="${CONFIG} --enable-vhost-vsock"
    - CONFIG="${CONFIG} --enable-avx2"
    - CONFIG="${CONFIG} --extra-cflags=' -O3 -fno-semantic-interposition -falign-functions=32 -D_FORTIFY_SOURCE=2 -fPIE -fuse-ld=gold'"
    - CONFIG="${CONFIG} --extra-ldflags=' -pie -z noexecstack -z relro -z now'"
script:
  - git submodule update --init --recursive --depth 500
  - mkdir -p /tmp/qemu-static/build
  - sudo mount -t tmpfs tmpfs /tmp/qemu-static/build
  - pushd /tmp/qemu-static/build
  - ${TRAVIS_BUILD_DIR}/qemu/configure "${CONFIG}"
  - popd
  - make -j $(nproc) -C /tmp/qemu-static/build
  - make -j $(nproc) -C /tmp/qemu-static/build install
  - tree /tmp/qemu-static/local
